export const common = {
  appName: 'Vidaro',
  browse: 'Browse',
  openFolder: 'Open folder',
  showInFolder: 'Show in folder',
  openFile: 'Open file',
  change: 'Change',
  cancel: 'Cancel',
  close: 'Close',
  dismiss: 'Dismiss',
  save: 'Save',
  saved: 'Saved',
  reset: 'Reset',
  resetAll: 'Reset all',
  resetToDefault: 'Reset to default',
  remove: 'Remove',
  retry: 'Retry',
  start: 'Start',
  pause: 'Pause',
  resume: 'Resume',
  copy: 'Copy',
  copied: 'Copied',
  details: 'Details',
  hideDetails: 'Hide details',
  learnMore: 'Learn more',
  more: 'More',
  none: 'None',
  on: 'On',
  off: 'Off',
  auto: 'Auto',
  keep: 'Keep',
  custom: 'Custom',
  default: 'Default',
  unknown: 'Unknown',
  loading: 'Loading…',
  selectAll: 'Select all',
  selectNone: 'Select none',
  yes: 'Yes',
  no: 'No',
  free: (size) => `${size} free`,
  items: (n) => (n === 1 ? '1 item' : `${n} items`),
  files: (n) => (n === 1 ? '1 file' : `${n} files`),
  update: 'Update',
  updateAvailable: (version) => `Update ${version}`,
  somethingWentWrong: 'Something went wrong',
  folderMissing: 'This folder does not exist yet. It will be created.'
};

export const nav = {
  download: 'Download',
  convert: 'Convert',
  queue: 'Queue',
  presets: 'Presets',
  settings: 'Settings'
};

export const status = {
  idle: 'Ready',
  downloading: (n) => (n === 1 ? '1 downloading' : `${n} downloading`),
  converting: (n) => (n === 1 ? '1 converting' : `${n} converting`),
  waiting: (n) => `${n} waiting`,
  totalSpeed: 'Total speed',
  diskFree: (drive, size) => `${drive} ${size} free`,
  diskLow: (drive, size) => `${drive} only ${size} free`
};
