const plural = (n, one, many) => (n === 1 ? one : many);

export const convert = {
  title: 'Convert',
  subtitle: 'Turn any video or audio into a file that plays everywhere',
  addFiles: 'Add files',
  addFolder: 'Add folder',
  dropTitle: 'Drop videos or audio here',
  dropOr: 'or',
  dropFormats: 'AVI, MOV, MKV, MP4, WMV, MPEG, VOB, DV, MTS, FLV, MP3, WAV and many more',
  reading: 'Reading files…',
  sourceLabel: 'Source',
  listSummary: (count, size, duration) => `${count} ${plural(count, 'file', 'files')} · ${size} · ${duration}`,
  probingCount: (n) => `Reading ${n}…`,
  clear: 'Clear',
  remove: 'Remove',
  trim: 'Trim',
  trimStart: 'Start',
  trimEnd: 'End',
  trimApply: 'Apply',
  trimClear: 'Clear trim',
  trimStartPlaceholder: '00:00:00.000',
  trimHint: 'Format hh:mm:ss.mmm. Leave End empty to keep the rest of the file.',
  trimBadge: (start, end) => `Trim ${start} – ${end}`,
  trimToEnd: 'end',
  trimErrors: {
    format: 'Use the format hh:mm:ss or hh:mm:ss.mmm.',
    startAfterEnd: 'The start must be before the end.',
    beyond: (duration) => `The file is only ${duration} long.`
  },
  readFailed: 'This file could not be read.',
  notConvertible: 'Cannot convert with these settings',
  analyze: 'Analyze',
  analyzing: 'Analyzing…',
  cancelAnalyze: 'Stop analyzing',
  analyzeHint: 'Checks about 600 frames to find out whether the video is interlaced or telecined film.',
  analyzeFailed: 'The analysis could not run.',
  analysis: {
    progressive: 'Progressive',
    tff: 'Interlaced · top field first',
    bff: 'Interlaced · bottom field first',
    telecine: 'Telecined film',
    unknown: 'Field order unclear'
  },
  analysisHints: {
    progressive: 'No interlacing found. The video is not deinterlaced.',
    tff: 'The video is deinterlaced when the preset uses Auto.',
    bff: 'The video is deinterlaced when the preset uses Auto.',
    telecine: 'Inverse telecine restores the original 23.976 fps when the preset uses Auto.',
    unknown: 'Not enough motion to decide. Auto settings follow what the file says.'
  },
  chips: {
    interlaced: 'Interlaced',
    'field-order-unknown': 'Field order unknown',
    vfr: 'Variable frame rate',
    hdr: 'HDR',
    'duration-estimated': 'Estimated duration',
    anamorphic: 'Non-square pixels',
    rotated: 'Rotated',
    'bitmap-subtitles': 'Image subtitles',
    'no-audio': 'No audio',
    'soft-telecine': 'Film (soft telecine)'
  },
  chipHints: {
    interlaced: 'Old TV video made of fields. Presets with Auto deinterlace fix it.',
    'field-order-unknown': 'The file does not say whether it is interlaced. Analyze to check it now, or it is checked during the conversion.',
    vfr: 'The frame rate changes over time, as in phone recordings. Constant frame rate avoids audio drift in editors.',
    hdr: 'High dynamic range video. It is converted to standard colors when the output needs it.',
    'duration-estimated': 'The file does not report a reliable length. Progress and trim times are approximate.',
    anamorphic: 'SD video with non-square pixels. Square pixels fixes its shape.',
    rotated: 'Recorded sideways. The rotation is applied when the video is re-encoded.',
    'bitmap-subtitles': 'Picture-based subtitles can only be kept in MKV.',
    'no-audio': 'This file has no sound.',
    'soft-telecine': 'Film stored at 23.976 fps with TV flags. It is kept as film.'
  },
  preset: 'Preset',
  presetPlaceholder: 'Custom settings',
  saveAsPreset: 'Save as preset',
  resetChanges: 'Reset changes',
  presetName: 'Preset name',
  presetNamePlaceholder: 'Name for these settings',
  savePreset: 'Save',
  cancel: 'Cancel',
  summaryTitle: 'Result',
  estimate: (size) => `≈ ${size}`,
  estimateTotal: (size) => `≈ ${size} in total`,
  estimateFirst: 'For the first file',
  encodersPending: 'Checking graphics encoders…',
  planWarnings: {
    'encoder-unavailable': 'The chosen encoder is not available on this PC. Another one will be used.',
    'encoder-mismatch': 'The chosen encoder does not match the codec. Another one will be used.',
    'encoder-container': 'This encoder cannot write this format. The software encoder will be used.',
    'two-pass-unavailable': 'Two-pass needs the software encoder, so one pass will be used.',
    'trim-keyframes': 'With video copy, cuts snap to the nearest keyframes.',
    'copy-ignores-picture': 'Picture settings are skipped because the video is copied.',
    'audio-reencoded': 'Some audio cannot be copied into this format and will be re-encoded.',
    'subtitles-dropped': 'Some subtitle tracks cannot be kept in this format.',
    'ivtc-not-applicable': 'Inverse telecine is skipped: the video is not 29.97 fps.',
    'no-audio': 'The file has no audio, so the result has no sound.'
  },
  outputTitle: 'Output file',
  saveTo: 'Save to',
  saveModes: { source: 'Next to the source', folder: 'Folder' },
  sourceFolderNote: 'Each file is saved in the folder of its original.',
  chooseFolder: 'Choose a folder',
  nameTemplate: 'File name',
  nameTemplateHint: 'Tokens: {name} original name, {resolution} output height, {preset} preset name, {date} today.',
  nameTemplateInvalid: 'The name must include {name}.',
  nameChips: ['{name}', '{name}_{resolution}', '{name} [{preset}]'],
  namePreview: (name) => `Example: ${name}`,
  collision: 'If the file exists',
  collisions: { rename: 'Add a number', overwrite: 'Overwrite', skip: 'Skip the file' },
  keepDate: 'Keep original date',
  keepDateHint: 'Copies the modified date of the source to the new file.',
  outputSummary: (template, collision) => `${template} · ${collision}`,
  addToQueue: 'Add to queue',
  convertAll: 'Convert all',
  waitProbing: 'Wait until all files are read',
  nothingReady: 'Add files that can be read first',
  fixSettings: 'Fix the highlighted settings first',
  needFolder: 'Choose an output folder first',
  added: (n) => `${n} ${plural(n, 'file was', 'files were')} added to the queue.`,
  started: (n) => `Started ${n} ${plural(n, 'conversion', 'conversions')}.`,
  viewQueue: 'View queue',
  notAdded: (n) => `${n} ${plural(n, 'file was', 'files were')} not added.`,
  enqueueFailed: 'The files could not be added to the queue.',
  noMediaFound: 'No video or audio files were found there.',
  alreadyAdded: (n) => `${n} ${plural(n, 'file is', 'files are')} already in the list.`,
  tooMany: (max) => `Only the first ${max} files were added.`,
  unknownDuration: '—'
};
