const plural = (n, one, many) => (n === 1 ? one : many);

export const presets = {
  title: 'Presets',
  subtitle: 'Saved conversion settings you can reuse',
  groupBuiltIn: 'Built-in',
  groupUser: 'Your presets',
  noUserPresets: 'Duplicate a preset to make your own.',
  modified: '(modified)',
  unsaved: 'Unsaved changes',
  defaultBadge: 'Default',
  isDefault: 'Default preset for new conversions',
  setDefault: 'Set as default',
  duplicate: 'Duplicate',
  duplicateToEdit: 'Duplicate to edit',
  rename: 'Rename',
  remove: 'Delete',
  exportPreset: 'Export',
  importPresets: 'Import',
  save: 'Save',
  discard: 'Discard changes',
  readOnly: 'Built-in presets are read-only. Duplicate to edit.',
  deleteTitle: (name) => `Delete “${name}”?`,
  deleteText: 'The preset is removed from this PC. Files already converted with it are not affected.',
  deleteConfirm: 'Delete preset',
  nameLabel: 'Preset name',
  nameRequired: 'Give the preset a name.',
  renameHint: 'Enter to save · Esc to cancel',
  imported: (n) => `Imported ${n} ${plural(n, 'preset', 'presets')}.`,
  importFailed: (names) => `Could not import ${names.join(', ')}. ${names.length === 1 ? 'It is' : 'They are'} not a valid Vidaro preset.`,
  nothingImported: 'No presets were imported.',
  actionFailed: 'The preset could not be changed.',
  loadFailed: 'The presets could not be loaded.',
  noSelection: 'Choose a preset on the left to see its settings.',
  missing: 'Custom settings',
  editor: {
    sections: {
      format: 'Format',
      video: 'Video',
      picture: 'Picture',
      audio: 'Audio'
    },
    kinds: {
      video: 'Video',
      audio: 'Audio only'
    },
    containers: {
      mp4: 'MP4',
      mkv: 'MKV',
      mov: 'MOV',
      webm: 'WebM',
      mp3: 'MP3',
      m4a: 'M4A (AAC)',
      wav: 'WAV',
      flac: 'FLAC',
      opus: 'Opus'
    },
    containerTags: {
      mp4: 'MP4',
      mkv: 'MKV',
      mka: 'MKA',
      mov: 'MOV',
      webm: 'WebM',
      mp3: 'MP3',
      m4a: 'M4A',
      wav: 'WAV',
      flac: 'FLAC',
      opus: 'Opus'
    },
    containerHints: {
      mp4: 'Plays everywhere: TVs, phones, editors and FlowAir.',
      mkv: 'Keeps any track and subtitle. Best for archives.',
      mov: 'For Apple devices and editing software.',
      webm: 'Open web format with VP9 or AV1 video.',
      mp3: 'Audio that plays on any device.',
      m4a: 'AAC audio, smaller than MP3 at the same quality.',
      wav: 'Uncompressed audio for editing and broadcast.',
      flac: 'Lossless compressed audio.',
      opus: 'Efficient audio for voice and streaming.'
    },
    outputType: 'Type',
    format: 'Format',
    subtitles: 'Subtitles',
    subtitleOptions: { keep: 'Keep', drop: 'Remove' },
    subtitlesAudioOnly: 'Audio formats cannot hold subtitles.',
    subtitlesHint: 'Text subtitles are converted when the format needs it.',
    faststart: 'Fast start',
    faststartHint: 'Lets the file start playing before it is fully loaded.',
    faststartUnavailable: 'Only for MP4, MOV and M4A.',
    videoMode: 'Video',
    audioMode: 'Audio',
    modes: { encode: 'Re-encode', copy: 'Copy', none: 'Remove' },
    videoCopyHint: 'The video is copied as it is: fast and without quality loss. Picture settings are not used.',
    videoNoneHint: 'The output has no video track.',
    videoAudioOnly: 'Audio formats have no video.',
    videoRemoveBlocked: 'Keep the audio to remove the video.',
    audioCopyHint: 'The audio is copied as it is. Tracks that do not fit the format are re-encoded.',
    audioNoneHint: 'The output has no sound.',
    audioRemoveBlocked: 'Keep the video to remove the audio.',
    codec: 'Codec',
    videoCodecs: { h264: 'H.264', hevc: 'HEVC (H.265)', av1: 'AV1', vp9: 'VP9' },
    videoCodecTags: { h264: 'H.264', hevc: 'HEVC', av1: 'AV1', vp9: 'VP9' },
    encoder: 'Encoder',
    encoderAuto: 'Auto (best available)',
    encoderMissing: (label) => `${label} (not on this PC)`,
    encoderBroken: (label) => `${label} (failed, not used)`,
    encoderDetecting: 'Checking the graphics encoders…',
    encoderSoftwareSetting: 'Settings use the software encoder only.',
    detectAgain: 'Detect again',
    rateControl: 'Rate control',
    rateControls: { quality: 'Constant quality', bitrate: 'Bitrate' },
    quality: 'Quality',
    qualityValue: (value, level) => `${value} (${level})`,
    qualityLevels: {
      veryHigh: 'very high',
      high: 'high',
      good: 'good',
      medium: 'medium',
      low: 'low',
      veryLow: 'very low'
    },
    qualityHint: 'Lower numbers keep more detail and make larger files.',
    bitrate: 'Bitrate',
    bitrateMode: 'Mode',
    bitrateModes: { vbr: 'VBR', cbr: 'CBR' },
    maxrate: 'Max bitrate',
    bufsize: 'Buffer size',
    zeroOff: '0 = off',
    kbps: 'kbps',
    twoPass: 'Two-pass encoding',
    twoPassHint: 'Better bitrate spread, twice the time. Software encoder (x264) only.',
    speed: 'Speed',
    speeds: { fast: 'Fast', balanced: 'Balanced', quality: 'Best' },
    speedHint: 'Slower settings make smaller files at the same quality.',
    profile: 'Profile',
    profiles: { auto: 'Auto', baseline: 'Baseline', main: 'Main', high: 'High' },
    level: 'Level',
    levelAuto: 'Auto',
    keyframes: 'Keyframe interval',
    keyframesHint: 'Seconds between keyframes. 0 = encoder default.',
    seconds: 's',
    pictureNotUsed: 'Picture settings apply only when the video is re-encoded.',
    resolution: 'Resolution',
    resolutionKeep: 'Keep original',
    resolutionCustom: 'Custom…',
    resolutionOption: (name, width, height) => `${name} (${width}×${height})`,
    width: 'Width',
    height: 'Height',
    px: 'px',
    fit: 'Fit',
    fits: { pad: 'Pad', crop: 'Crop', stretch: 'Stretch', fit: 'Fit' },
    fitHints: {
      pad: 'Adds black bars so the whole picture fits the frame.',
      crop: 'Fills the frame and cuts the edges that do not fit.',
      stretch: 'Fills the frame and changes the proportions.',
      fit: 'Scales to fit inside the size, without bars.'
    },
    noUpscale: 'Never enlarge',
    noUpscaleHint: 'Smaller videos keep their size.',
    frameRate: 'Frame rate',
    frameRateKeep: 'Keep original',
    frameRateCustom: 'Custom…',
    customFps: 'Custom rate',
    customFpsPlaceholder: 'e.g. 15 or 12000/1001',
    customFpsInvalid: 'Enter a rate between 1 and 240, like 15, 29.97 or 30000/1001.',
    fps: 'fps',
    cfr: 'Constant frame rate',
    cfrHint: 'Recommended for editing and broadcast. Phone videos often use a variable rate.',
    deinterlace: 'Deinterlace',
    deinterlaceRate: 'Deinterlaced output',
    deinterlaceRates: { frame: 'Per frame', field: 'Per field' },
    deinterlaceRateHints: {
      frame: 'Keeps the frame rate: 29.97i becomes 29.97p.',
      field: 'Doubles the frame rate for smoother motion: 29.97i becomes 59.94p.'
    },
    triState: { auto: 'Auto', off: 'Off', on: 'On' },
    ivtc: 'Inverse telecine',
    ivtcHint: 'Restores 23.976 fps film that was converted to 29.97 fps for TV.',
    squarePixels: 'Square pixels',
    squarePixelsHint: 'Fixes the shape of SD video (DV, DVD) so it looks right everywhere.',
    colorConvert: 'SD to HD colors',
    colorConvertHint: 'Converts BT.601 colors to BT.709 when SD video is scaled up.',
    colorOptions: { auto: 'Auto', off: 'Off' },
    rotate: 'Rotate',
    rotations: { 0: '0°', 90: '90°', 180: '180°', 270: '270°' },
    flip: 'Flip',
    flipH: 'Horizontal',
    flipV: 'Vertical',
    crop: 'Crop borders',
    cropSides: { top: 'Top', bottom: 'Bottom', left: 'Left', right: 'Right' },
    cropHint: 'Pixels removed from each side of the source, before scaling.',
    audioCodecs: { aac: 'AAC', mp3: 'MP3', opus: 'Opus', ac3: 'AC-3', pcm: 'PCM 16-bit', flac: 'FLAC', vorbis: 'Vorbis' },
    audioCodecTags: { aac: 'AAC', mp3: 'MP3', opus: 'Opus', ac3: 'AC-3', pcm: 'PCM', flac: 'FLAC', vorbis: 'Vorbis' },
    audioBitrate: 'Bitrate',
    kbpsValue: (value) => `${value} kbps`,
    losslessBitrate: 'Set by the format',
    vbr: 'MP3 VBR',
    vbrOff: 'Off (constant bitrate)',
    vbrLevel: (level) => (level === 0 ? 'V0 (best)' : level === 8 ? 'V8 (smallest)' : `V${level}`),
    sampleRate: 'Sample rate',
    sampleRates: { keep: 'Keep', 44100: '44.1 kHz', 48000: '48 kHz' },
    opusRate: 'Opus always uses 48 kHz.',
    channels: 'Channels',
    channelOptions: { keep: 'Keep', stereo: 'Stereo', mono: 'Mono' },
    volume: 'Volume',
    volumeValue: (db) => (db === 0 ? '0 dB' : `${db > 0 ? '+' : '−'}${Math.abs(db).toFixed(1)} dB`),
    loudness: 'Loudness normalization',
    loudnessOptions: {
      off: 'Off',
      ebu: 'EBU R128 · −23 LUFS',
      atsc: 'ATSC A/85 · −24 LKFS',
      streaming: 'Streaming · −14 LUFS'
    },
    loudnessTags: { ebu: 'EBU R128', atsc: 'ATSC A/85', streaming: '−14 LUFS' },
    loudnessHint: 'Measures the whole file first, then sets an even level. Takes a little longer.',
    tracks: 'Tracks',
    trackOptions: { first: 'Main track', all: 'All tracks' },
    tracksAudioOnly: 'Audio formats keep one track.',
    summary: {
      notUsed: 'Not used',
      copy: 'Copy',
      noVideo: 'No video',
      noAudio: 'No audio',
      keepSize: 'Original size',
      keepRate: 'Original rate',
      quality: (value) => `Quality ${value}`,
      kbps: (value) => `${value} kbps`,
      subtitles: 'Subtitles',
      fastStart: 'Fast start',
      twoPass: '2-pass',
      deinterlace: 'Deinterlace',
      ivtc: 'IVTC',
      rotated: (degrees) => `${degrees}°`,
      cropped: 'Cropped',
      flipped: 'Flipped',
      allTracks: 'All tracks',
      lossless: 'Lossless',
      pcm: 'PCM 16-bit',
      audioCopy: 'Audio copy',
      videoCopy: 'Video copy',
      vbr: (level) => `VBR V${level}`,
      khz: (value) => `${value} kHz`,
      fpsTag: (value) => `${value} fps`
    }
  }
};
